/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyApp {
    }
    interface MyContentPage {
        "content": () => any;
        "header": string;
    }
    interface MyPage {
        "s1": string;
        "s2": string;
        "s3": string;
    }
}
declare global {
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyContentPageElement extends Components.MyContentPage, HTMLStencilElement {
    }
    var HTMLMyContentPageElement: {
        prototype: HTMLMyContentPageElement;
        new (): HTMLMyContentPageElement;
    };
    interface HTMLMyPageElement extends Components.MyPage, HTMLStencilElement {
    }
    var HTMLMyPageElement: {
        prototype: HTMLMyPageElement;
        new (): HTMLMyPageElement;
    };
    interface HTMLElementTagNameMap {
        "my-app": HTMLMyAppElement;
        "my-content-page": HTMLMyContentPageElement;
        "my-page": HTMLMyPageElement;
    }
}
declare namespace LocalJSX {
    interface MyApp {
    }
    interface MyContentPage {
        "content"?: () => any;
        "header"?: string;
    }
    interface MyPage {
        "s1"?: string;
        "s2"?: string;
        "s3"?: string;
    }
    interface IntrinsicElements {
        "my-app": MyApp;
        "my-content-page": MyContentPage;
        "my-page": MyPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-content-page": LocalJSX.MyContentPage & JSXBase.HTMLAttributes<HTMLMyContentPageElement>;
            "my-page": LocalJSX.MyPage & JSXBase.HTMLAttributes<HTMLMyPageElement>;
        }
    }
}
